version: '3.1'

services:
  debug:
    networks:
      - mynet
    container_name: debug
    image: busybox:latest
    stdin_open: true
    tty: true
  backend:
    networks:
      - mynet
    container_name: backend
    image: backend:latest
    restart: always
    depends_on:
      - database
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/frienddb"
  database:
    networks:
      - mynet
    container_name: database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: frienddb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    networks:
      - mynet
    container_name: adminer
    image: adminer
    restart: always
    expose:
      - 9000
    ports:
      - "9000:8080"
volumes:
  my-db:
networks:
  mynet: