version: '3.1'

services:
  backend:
    networks:
      - mynet
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend:latest
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/frienddb"
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
  database:
    networks:
      - mynet
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_DATABASE: frienddb
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    networks:
      - mynet
    container_name: adminer
    image: adminer
    expose:
      - 9000
    ports:
      - "9000:8080"
    restart: always
  debug:
    networks:
      - mynet
    container_name: debug
    image: busybox:latest
    stdin_open: true
    tty: true
volumes:
  my-db:
networks:
  mynet: