version: '3.1'

services:
  backend:
    image: backend:latest
    restart: always
    networks:
      - mynet
    depends_on:
      - database
    expose:
      - 8080
    ports:
      - "8080:8080"
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynet
    environment:
      MYSQL_DATABASE: frienddb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: adminer
    networks:
      - mynet
    restart: always
    expose:
      - 9000
    ports:
      - "9000:8080"
volumes:
  my-db:
networks:
  mynet: