version: '3.1'

services:

  springboot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db


  backend:
    build: .
    restart: always
    ports:
      - "8090:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/studentdb"

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"

volumes:
  my-db: