###
# http://localhost:8080/api/v1
# GET = /friends

GET http://localhost:8080/api/v1/friends
Accept: application/json


###
# DELETE = /friends/id

DELETE http://localhost:8080/api/v1/friends/2
Accept: application/json


###
# PUT = /friends/id?name=...&age=...

PUT http://localhost:8080/api/v1/friends/20?name=Herbert&age=50
Content-Type: application/json


###
# POST = friends/add

POST http://localhost:8080/api/v1/friends/add
Content-Type: application/json

{
  "name": "Kenny",
  "age": 24
}