###
# http://localhost:8080/api/v1
# GET = /friends

GET http://localhost:8080/api/v1/friends
Accept: application/json

###
# DELETE = /id

DELETE http://localhost:8080/api/v1/friends/2
Accept: application/json

###
# PUT = /id?id=...&name=...&age=...

PUT http://localhost:8080/api/v1/friends/1?name=Tim&age=40
Content-Type: application/json

###



# Doesn't Work :(
# POST =

POST http://localhost:8080/api/v1/friends
Content-Type: application/json

{
  "id": 0,
  "name": "JOHNNY SINS",
  "age": 28
}